services:
  frontend:
    build: ./frontend

    container_name: next-certificados

    ports:
      - "3000:3000"
    
    volumes:
      - ./frontend:/app
      - /app/node_modules
    
    depends_on:
      - python-api

  python-api:
    build: ./api-python

    container_name: flask-certificados

    ports:
      - "5000:5000"